### ISSUE TITLE
Handle links in IEFrame

### ISSUE THREAD

**Issue by JohnSpahr** [Pocket-PC-Planet/PPCP-AppManager#28] opened 2020-12-04 03:11 UTC
Title says it all.

**Comment by carcarjg** [comment] 2020-12-04 03:14
Current progress: Links are being taken apart.
TODO: Take the results and do something with it.

**Comment by carcarjg** [comment] 2020-12-04 03:14
Also, Duplicate of #26

**Comment by JohnSpahr** [comment] 2020-12-04 12:33
Oh, whoops

**Closed** 2020-12-04 12:34 UTC
Labels: Core, duplicate, todo :spiral_notepad:
